version: 2.1
#orbs:
#  node: circleci/node@4.7
jobs:
  build:
    docker:
      - image: cimg/base:2023.02
    steps:
      - checkout
      - run: sudo pip install npm
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules/
      - run: npm run lint
  test:
    docker:
      - image: cimg/base:2023.02
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_packages"
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: cimg/base:2023.02
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_packages"
#      - run: npm i
      - run: npm audit
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
